Repository canonical-web-and-design/generator-canonical-webteam, pull requests merged in 2019-03, with the labels that each got.

#101 Removes css-nano
  generators/run/templates/package.json
Labels: Review: Code +1

#102 Add back database support for Django sites
  CHANGES.txt
  generators/run/templates/run
  package.json
Labels: Review: Code needed, Review: QA needed

#103 Spin up a database for ./run exec as well
  CHANGES.txt
  generators/run/templates/run
  package.json
Labels: Review: Code needed, Review: QA needed

#104 v3.3.2: Better database management
  CHANGES.txt
  generators/run/templates/run
  package.json
Labels: Review: Code needed, Review: QA +1
